export const generateProductExternError = (userId) => {
   return `
   Hubo un error al generar productos masivos con FAKER
   `
}